modules/admin/models/Users.php
<?php

namespace app\modules\admin\models;

use app\models\User;
use phpDocumentor\Reflection\DocBlock\Tags\Var_;
use Yii;
use yii\behaviors\TimestampBehavior;
use \yii\db\ActiveRecord;
use yii\db\Expression;
use app\components\behaviors\CutomBehaviors;
use yii\helpers\VarDumper;
use yii\web\IdentityInterface;

class Users extends BaseModel implements IdentityInterface
{
    public $item_name;

    public static function tableName()
    {
        return '{{%users}}';
    }

    public function rules()
    {
        return [
            [['name', 'surname', 'username', 'password'], 'required'],
            [['created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['name'], 'string', 'max' => 70],
            [['surname'], 'string', 'max' => 60],
            [['username', 'password'], 'string', 'max' => 100],
            [['username'], 'unique'],
            [['item_name'], 'string']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'username' => 'Username',
            'password' => 'Password',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
    }

    public static function findByUsername($username)
    {
        return self::findOne([
            'username' => $username
        ]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
//        return $this->authKey;
    }

    public function validateAuthKey($authKey)
    {
//        return $this->authKey === $authKey;
    }

    public function setPassword($password)
    {
        $this->password = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    public function getUserDepartments()
    {
        return $this->hasMany(UserDepartment::className(), ['user_id' => 'id']);
    }

    public function getShow($d){
        $i = 0;
        $str = '';
        foreach ($d as $r){
            $str .= "<tr data-key='".$i."'><td>".$r['item_name']."</td><td><input type='checkbox' value=".$r['item_name']." class='items'></td><td><input type='checkbox' value=".$r['item_name']." class='items-update'></td></tr>";
            $i++;
        }
        return $str;
    }

}

modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\AuthAssignment;
use app\modules\admin\models\AuthItem;
use Yii;
use app\modules\admin\models\Users;
use app\modules\admin\models\UsersSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Application;

class UsersController extends BaseController
{
    public function behaviors()
    {
        parent::behaviors();
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['Administrator'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionOne(){
        $id = Yii::$app->request->get('id');

        return $this->render('one', compact('id'));
    }

    public function actionCreate()
    {
        $model = new Users();
        $assig = AuthItem::find()
            ->asArray()
            ->all();

        if ($model->load(Yii::$app->request->post())) {
            Yii::$app->session->set('username', $model->username);
            $model->setPassword($model->password);
            $model->save();

            return $this->redirect(['users/add-assignment']);
        }

        return $this->render('create', [
            'model' => $model,
            'assig' => $assig,
        ]);
    }

    public function actionDel(){
        $model = new Users();
        $id = Yii::$app->request->get('id');
        $array = Yii::$app->request->get('array');
        if(Yii::$app->request->isAjax)
            $this->layout = false;
        $sql = "DELETE FROM auth_assignment WHERE user_id = $id AND ";
        foreach ($array as $r){
            $sql .= " item_name = '{$r}' OR ";
        }
        $sql = rtrim($sql, 'OR ');
        $res = Yii::$app->db->createCommand($sql);
        $res->queryAll();
        $data = Yii::$app->db->createCommand("SELECT * FROM auth_assignment WHERE user_id = $id");
        $r = $data->queryAll();
        return $this->render('del', compact('r'));
    }

    public function actionAll(){
        $model = new Users();
        $id = Yii::$app->request->get('id');
        $row = AuthAssignment::find()
            ->asArray()
            ->where(['user_id' => $id])
            ->all();
        if(empty($row)) {
            $row = '<tr></tr>';
            return $row;
        }
        return $model->getShow($row);
    }

    public function actionUpdateAll(){
        $id = Yii::$app->request->get('id');
        $array = Yii::$app->request->get('array');
        $sql = "SELECT * FROM auth_assignment WHERE user_id = $id AND ";
        foreach($array as $r){
            $sql .= " item_name = '{$r}' OR ";
        }
        if(Yii::$app->request->isAjax)
        {
            $this->layout = false;
        }
        $item = AuthItem::find()->asArray()->all();
        $user = Users::find()->asArray()->all();
        $sql = rtrim($sql, 'OR ');
        $result = Yii::$app->db->createCommand($sql);
        $res = $result->queryAll();
        return $this->render('update_all', compact('res', 'item', 'user'));
    }

    public function actionUpdateData(){
        $id = Yii::$app->request->get('id');
        $items = Yii::$app->request->get('items');
        $users = Yii::$app->request->get('users');
        $old_users = Yii::$app->request->get('old_users');
        $old_items = Yii::$app->request->get('old_items');
        debug($old_users);
        debug($old_items);
        $i = 0;
        $sql = "SELECT * FROM auth_assignment WHERE user_id = $id AND ";
        foreach($old_users as $r){
            $sql .= " user_id = $r AND item_name = '{$old_items[$i]}' AND ";
            $i++;
        }
        $sql = rtrim($sql, ' AND ');
        $result = Yii::$app->db->createCommand($sql);
        $res = $result->queryAll();
        $sum = 0;
        $query = "INSERT INTO auth_assignment (item_name, user_id) VALUES (";
        foreach($res as $r){
            $query .= "'".addslashes($items[$sum])."', '".addslashes($users[$sum])."'), (";
            $sum++;
        }
        $query = rtrim($query, ', (');
        $res = Yii::$app->db->createCommand($query);
        $all = $res->queryAll();
        return true;
    }

    public function actionAddAssignment(){
        $model = new AuthAssignment();
        $item = AuthItem::find()
            ->asArray()
            ->all();
        $users = Users::find()
            ->asArray()
            ->where(['username' => Yii::$app->session->get('username')])
            ->all();

        if($model->load(Yii::$app->request->post()) && $model->save()){
            Yii::$app->session->setFlash('success', 'Foydalanuvchiga huquq berildi!');
            return $this->redirect(['auth-assignment/index']);
        }

        return $this->render('assig', compact('model', 'users', 'item'));
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/users/assig.php
<?php
    use yii\bootstrap\ActiveForm;
    use yii\helpers\Html;

    $f = ActiveForm::begin();
        echo $f->field($model, 'item_name')->widget(\kartik\select2\Select2::className(),[
            'data' => \yii\helpers\ArrayHelper::map($item, 'name', 'name')
        ]);
        echo $f->field($model, 'user_id')->widget(\kartik\select2\Select2::className(),[
            'data' => \yii\helpers\ArrayHelper::map($users, 'id', 'name'),
        ]);
        echo Html::submitButton('Crud', ['class' => 'btn btn-info btn-sm']);
    ActiveForm::end();

modules/admin/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'assig' => $assig,
    ]) ?>

</div>

modules/admin/views/users/del.php
<?php
    debug($r);

modules/admin/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Users', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            'surname',
            'username',
            [
                'attribute' => 'created_at',
                'label' => 'Foydalanuvchi huquqi',
                'format' => 'html',
                'value' => function($res){
                    $result = \app\modules\admin\models\AuthAssignment::find()
                        ->asArray()
                        ->where(['user_id' => $res->id])
                        ->all();
                    foreach ($result as $r){
                        return "<a href='".\yii\helpers\Url::to(['users/one', 'id' => $r['user_id']])."'>".$r['item_name']."</a>";
                    }
                }
            ],
//            'password',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

modules/admin/views/users/one.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\grid\GridView;

    $dataProvider = new \yii\data\SqlDataProvider([
       'sql' => "SELECT * FROM auth_assignment WHERE user_id = $id",
    ]);

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'showHeader' => true,
        'columns' => [
            'item_name',
            [
                'attribute' => 'item_name',
                'label' => 'delete',
                'format' => 'raw',
                'value' => function($res){
                    return '<input type="checkbox" value="'.$res['item_name'].'" class="items">';
                }
            ],
            [
                'attribute' => 'item_name',
                'label' => 'update',
                'format' => 'raw',
                'value' => function($res){
                    return '<input type="checkbox" value="'.$res['item_name'].'" class="items-update">';
                }
            ],

        ],
    ]);
    ?>
    <button class="btn btn-info btn-sm" data-id="<?=$id?>" id="delItems">Delete</button>
    <button class="btn btn-success btn-sm" data-id="<?=$id?>" id="updateItems">Update</button>

modules/admin/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */

$this->title = 'Update Users: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/users/update_all.php
<?php
    use yii\bootstrap\ActiveForm;
    use yii\helpers\Html;
    ?>
<div class="container">
    <div class="row">
        <table class="table" style="width: 70%">
            <thead>
                <th>ID</th><th>ITEM_NAME</th><th>user_id</th>
            </thead>
            <tbody>
            <form action="" data-id="<?=$_GET['id']?>" id="selection" method="post">
                <?php $i = 1; foreach($res as $r): ?>
                    <tr>
                        <td><?=$i?></td>
                        <td><select name="item_name" id="" class="form-control item_name">
                                <?php foreach ($item as $row): ?>
                                    <option <?php
                                        if($r['item_name'] === $row['name']) echo 'selected'
                                    ?>><?=$row["name"]?></option>
                                <?php endforeach; ?>
                            </select></td>
                        <td>
                            <select name="user_id" id="" class="form-control user_id">
                            <?php foreach ($user as $row): ?>
                                <option value="<?=$row['id']?>" <?php
                                if($r['user_id'] === $row['id']) echo 'selected'
                                ?>><?=$row['name']?></option>
                            <?php endforeach; ?>
                            </select></td>
                    </tr>
                <?php $i++; endforeach; ?>
                <input type="submit" name="ok" id="myButton" value="Update" class="btn btn-info btn-sm">
            </form>
            </tbody>
            <tfoot>

            </tfoot>
        </table>
    </div>
</div>

modules/admin/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'surname',
            'username',
            'password',
            'created_at',
            'updated_at',
            'created_by',
            'updated_by',
        ],
    ]) ?>

</div>